# Local Postgresql Database Lab

In this lab we will practice adding and removing data from a local Postgresql database. We will:

- Walk through instructions on how to set up and configure a local postgresql server
- Create a database and a table using SQL and CRUD data in/from that table.
- Learn how to copy data from a CSV file into this local database
- Practice our SQL with a practice assignment.

## 1. Install PostgreSQL locally

You should have already taken care of this in the Installfest, but just in case, [here](http://www.postgresql.org/download/) are the instructions for the most common platforms.

## 2. Launch and connect to a local PostgreSQL server

Now that you've installed PostgreSQL locally, practice connecting with the following methods:
- Command-line (psql)
- Sqlalchemy + Pandas
- Ipython-notebook using the ipython-sql extension

**Check:** List the existing databases, there should be none, right?
> not true, there are some default databases from postgres

**Check:** If there are databases, check the tables' contents. Hint: information_schema.tables

In [10]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine('postgresql://localhost:5432/allenbyron')
pd.read_sql('select * from information_schema.tables;', engine)

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,allenbyron,public,test,BASE TABLE,None,None,None,None,None,YES,NO,None
1,allenbyron,pg_catalog,pg_statistic,BASE TABLE,None,None,None,None,None,YES,NO,None
2,allenbyron,pg_catalog,pg_type,BASE TABLE,None,None,None,None,None,YES,NO,None
3,allenbyron,public,globalgoals,BASE TABLE,None,None,None,None,None,YES,NO,None
4,allenbyron,pg_catalog,pg_authid,BASE TABLE,None,None,None,None,None,YES,NO,None
5,allenbyron,pg_catalog,pg_roles,VIEW,None,None,None,None,None,NO,NO,None
6,allenbyron,pg_catalog,pg_shadow,VIEW,None,None,None,None,None,NO,NO,None
7,allenbyron,pg_catalog,pg_group,VIEW,None,None,None,None,None,YES,NO,None
8,allenbyron,pg_catalog,pg_user,VIEW,None,None,None,None,None,NO,NO,None
9,allenbyron,pg_catalog,pg_policies,VIEW,None,None,None,None,None,NO,NO,None
10,allenbyron,pg_catalog,pg_settings,VIEW,None,None,None,None,None,NO,NO,None
11,allenbyron,pg_catalog,pg_rules,VIEW,None,None,None,None,None,NO,NO,None
12,allenbyron,pg_catalog,pg_file_settings,VIEW,None,None,None,None,None,NO,NO,None
13,allenbyron,pg_catalog,pg_views,VIEW,None,None,None,None,None,NO,NO,None
14,allenbyron,pg_catalog,pg_tables,VIEW,None,None,None,None,None,NO,NO,None
15,allenbyron,pg_catalog,pg_matviews,VIEW,None,None,None,None,None,NO,NO,None
16,allenbyron,pg_catalog,pg_indexes,VIEW,None,None,None,None,None,NO,NO,None
17,allenbyron,pg_catalog,pg_stats,VIEW,None,None,None,None,None,NO,NO,None
18,allenbyron,pg_catalog,pg_locks,VIEW,None,None,None,None,None,NO,NO,None
19,allenbyron,pg_catalog,pg_cursors,VIEW,None,None,None,None,None,NO,NO,None
20,allenbyron,pg_catalog,pg_available_extensions,VIEW,None,None,None,None,None,NO,NO,None
21,allenbyron,pg_catalog,pg_available_extension_versions,VIEW,None,None,None,None,None,NO,NO,None
22,allenbyron,pg_catalog,pg_prepared_xacts,VIEW,None,None,None,None,None,NO,NO,None
23,allenbyron,pg_catalog,pg_prepared_statements,VIEW,None,None,None,None,None,NO,NO,None
24,allenbyron,pg_catalog,pg_seclabels,VIEW,None,None,None,None,None,NO,NO,None
25,allenbyron,pg_catalog,pg_timezone_abbrevs,VIEW,None,None,None,None,None,NO,NO,None
26,allenbyron,pg_catalog,pg_timezone_names,VIEW,None,None,None,None,None,NO,NO,None
27,allenbyron,pg_catalog,pg_stat_all_tables,VIEW,None,None,None,None,None,NO,NO,None
28,allenbyron,pg_catalog,pg_stat_xact_all_tables,VIEW,None,None,None,None,None,NO,NO,None
29,allenbyron,pg_catalog,pg_stat_sys_tables,VIEW,None,None,None,None,None,NO,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...
148,allenbyron,information_schema,role_table_grants,VIEW,None,None,None,None,None,NO,NO,None
149,allenbyron,information_schema,tables,VIEW,None,None,None,None,None,NO,NO,None
150,allenbyron,information_schema,transforms,VIEW,None,None,None,None,None,NO,NO,None
151,allenbyron,information_schema,triggered_update_columns,VIEW,None,None,None,None,None,NO,NO,None
152,allenbyron,information_schema,triggers,VIEW,None,None,None,None,None,NO,NO,None
153,allenbyron,information_schema,udt_privileges,VIEW,None,None,None,None,None,NO,NO,None
154,allenbyron,information_schema,role_udt_grants,VIEW,None,None,None,None,None,NO,NO,None
155,allenbyron,information_schema,usage_privileges,VIEW,None,None,None,None,None,NO,NO,None
156,allenbyron,information_schema,role_usage_grants,VIEW,None,None,None,None,None,NO,NO,None
157,allenbyron,information_schema,user_defined_types,VIEW,None,None,None,None,None,NO,NO,None
158,allenbyron,information_schema,view_column_usage,VIEW,None,None,None,None,None,NO,NO,None
159,allenbyron,information_schema,view_routine_usage,VIEW,None,None,None,None,None,NO,NO,None
160,allenbyron,information_schema,view_table_usage,VIEW,None,None,None,None,None,NO,NO,None
161,allenbyron,information_schema,views,VIEW,None,None,None,None,None,NO,NO,None
162,allenbyron,information_schema,data_type_privileges,VIEW,None,None,None,None,None,NO,NO,None
163,allenbyron,information_schema,element_types,VIEW,None,None,None,None,None,NO,NO,None
164,allenbyron,information_schema,_pg_foreign_table_columns,VIEW,None,None,None,None,None,NO,NO,None
165,allenbyron,information_schema,column_options,VIEW,None,None,None,None,None,NO,NO,None
166,allenbyron,information_schema,_pg_foreign_data_wrappers,VIEW,None,None,None,None,None,NO,NO,None
167,allenbyron,information_schema,foreign_data_wrapper_options,VIEW,None,None,None,None,None,NO,NO,None
168,allenbyron,information_schema,foreign_data_wrappers,VIEW,None,None,None,None,None,NO,NO,None
169,allenbyron,information_schema,_pg_foreign_servers,VIEW,None,None,None,None,None,NO,NO,None
170,allenbyron,information_schema,foreign_server_options,VIEW,None,None,None,None,None,NO,NO,None
171,allenbyron,information_schema,foreign_servers,VIEW,None,None,None,None,None,NO,NO,None
172,allenbyron,information_schema,_pg_foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
173,allenbyron,information_schema,foreign_table_options,VIEW,None,None,None,None,None,NO,NO,None
174,allenbyron,information_schema,foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
175,allenbyron,information_schema,_pg_user_mappings,VIEW,None,None,None,None,None,NO,NO,None
176,allenbyron,information_schema,user_mapping_options,VIEW,None,None,None,None,None,NO,NO,None
177,allenbyron,information_schema,user_mappings,VIEW,None,None,None,None,None,NO,NO,None

## 3. Create DB
Once you are connected to your local Postgresql server, create a new database. Call it `lab33`.

Practice creating and deleting the database with the following methods:
- Command-line:
>     CREATE database lab33;
>     DROP database lab33;

- Sqlalchemy
- Ipython-notebook using the ipython-sql extension

## 4. CRUD (Create, Read, Update, and Delete)

In lesson 1.1 you learned how to add and remove data from sqlite. Let's review that on our local PostgreSQL installation.

### 4.a: Creating Tables and Adding Columns

1. Create an table called `table1` with a single column `field1` containing an INTEGER PRIMARY KEY. Practice doing this with any of the methods above.
- Add a few more columns to `table1`:
    - field2 VARCHAR(16)
    - field3 REAL
    - field4 TEXT
check [the doc](http://www.postgresql.org/docs/9.3/static/datatype.html) for more info on data types supported by postgresql.
- Check tables and schemas using command line or postico

### 4.b: Add Data

Add some data to `table1`:

|field1|field2|field3|field4|
|----|
|1|'Henry James'|42|'75 Mission Street, San Francisco, CA'|
|2|'Carol James'|40|'75 Mission Street, San Francisco, CA'|
|3|'Jesse James'|12|'75 Mission Street, San Francisco, CA'|

### 4.c: Read Data
Read the content of the table,

### 4.d: Update Records
Suppose we need to update an existing record with new data - e.g. maybe `Jesse James` is only 9. Use the update command to do this.

### 4.e: Remove Records
To remove records use the DELETE command. Delete the entry for anyone matching `Jesse`.

## 5. Data from CSV

Copy CSV data from a local file into a local PostgreSQL database. We will use a [dataset](../../assets/datasets/Eviction_Notices.csv) pulled from the SF open data website. It contains a set of eviction notices issued in San Francisco.

Open the data in a text editor and have a look at it.

### 5.a: Simple Import

Read [this post](http://stackoverflow.com/questions/2987433/how-to-import-csv-file-data-into-a-postgresql-table) to learn how you can import data from CSV to PostgreSQL.

Notice that you have to decide the type for each column. Let's keep it simple and import everything as a string of text for now.

- Create a table called `evictions_simple` and import the data as varchar.
- Check that everything worked fine by loading a few lines from the table.
- Try some simple queries:
    - count how many evictions are due to non_payments
    - list the 3 most recent evictions


**Hint:** A good practice when you create a new table is to always drop it first, in case it already exists.

**Check:** Did you avoid importing the header as a record?

### 5.b: Data Cleaning and Import

If you've executed the last query correctly (most recent evictions), you'll have noticed that the dates are not correctly understood. This is because we were sloppy and imported the data as string for all fields.

Let's see what data types we would ideally like to have for each column.

[Here are data types](http://www.tutorialspoint.com/postgresql/postgresql_data_types.htm)

- Discuss in pairs each column and then let's summarize together. Which data type would you choose for each field?
- Repeat the import to a new table called `evictions`. Notice that line 31494 may throw an error. Why is that?
> There are two ` characters that do not belong.
- Repeat the query for the 3 most recent evictions. Does it work now?

## 6. Queries

Now that we have imported the data with correct data types, let's query the `evictions` table and find out a few things about SF and evictions.

Questions:
- How many neighborhoods are there in SF? List them alphabetically
- How many supervisor districts? 
- How many unique zip codes?
    - Are there any bad data in these? how many?
- What are the top 5 causes of eviction?

### 6.a: How many neighborhoods are there in SF? List them alphabetically.

### 6.b: How many supervisor districts?

### 6.c how many unique zip codes?

Are there any bad data in these?

### 6.d: What are the top 5 causes of eviction?

You may find it easier to answer this question using pandas.

## Bonus
- Let's count the number of evictions for each year
    - How has the number varied?
    - Can you compare this with the nasdaq index? (use the DataReader module in Pandas to get the data)