# Aquire and join data soureces

In [1]:
%matplotlib inline
import pandas as pd

In [20]:
drinks = pd.read_csv('national-drinking-habits.csv')

### Note: if no header you would not have columns

In [16]:
wiki_page = 'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population'
dfs = pd.read_html(wiki_page, header=0, index_col=0)

In [5]:
len(dfs)

4

In [6]:
dfs[0].shape

(1, 2)

In [9]:
dfs[2].shape

(251, 6)

In [17]:
dfs[2]

,Country (or dependent territory),Population,Date,% of world population,Source
Rank,,,,,
1,China[Note 2],1378640000,"September 8, 2016",18.8%,Official population clock
2,India,1330730000,"September 8, 2016",18.1%,Official population clock
3,United States[Note 3],324429000,"September 8, 2016",4.42%,Official population clock
4,Indonesia,260581000,"July 1, 2016",3.55%,Official projection
5,Brazil,206625000,"September 8, 2016",2.81%,Official population clock
6,Pakistan,194196000,"September 8, 2016",2.64%,Official population clock
7,Nigeria,186988000,"July 1, 2016",2.55%,UN Projection
8,Bangladesh,161047000,"September 8, 2016",2.19%,Official population clock
9,Russia[Note 4],146640000,"May 1, 2016",2%,Official estimate
10,Mexico,128632000,"July 1, 2016",1.75%,Official projection
11,Japan,127000000,"August 1, 2016",1.73%,Monthly provisional estimate
12,Philippines,102981000,"September 8, 2016",1.4%,Official population clock
13,Vietnam,92700000,"July 1, 2016",1.26%,Annual official projection
14,Ethiopia,92206005,"July 1, 2016",1.26%,Official projection
15,Egypt,91545900,"September 8, 2016",1.25%,Official population clock
16,Democratic Republic of the Congo,82310000,"July 1, 2016",1.12%,Official estimate
17,Germany,82175700,"December 30, 2015",1.12%,Official estimate
18,Iran,79519600,"September 8, 2016",1.08%,Official population clock
19,Turkey,78742000,"December 31, 2015",1.07%,Annual official estimate
20,France[Note 5],66736000,"July 1, 2016",0.88%,Monthly official estimate
21,Thailand,65729098,"December 31, 2015",0.89%,Annual official estimate
22,United Kingdom,65110000,"July 1, 2015",0.89%,Annual official estimate
23,Italy,60665551,"January 1, 2016",0.83%,Official estimate
24,South Africa,55653654,"July 1, 2016",0.76%,Annual official estimate
25,Tanzania[Note 6],55155000,"July 1, 2016",0.75%,UN projection
26,Myanmar,54363426,"July 1, 2016",0.74%,UN projection
27,South Korea,50617045,"January 6, 2016",0.69%,Annual official estimate
28,Colombia,48827400,"September 8, 2016",0.665%,Official population clock
29,Kenya,47251000,"July 1, 2016",0.64%,UN projection
30,Spain,46438422,"January 1, 2016",0.63%,Official estimate
...,...,...,...,...,...
188,Saint Kitts and Nevis,46204,"May 15, 2011",0.00063%,2011 census result
189,Monaco,38400,"December 31, 2015",0.00052%,Annual official estimate
--,Sint Maarten (Netherlands),38247,"January 1, 2015",0.00052%,Official estimate
190,Liechtenstein,37623,"December 31, 2015",0.00051%,Semi annual official estimate
--,Saint-Martin (France),36457,"January 1, 2015",0.0005%,Annual official estimate
--,Gibraltar (UK),33140,"December 31, 2014",0.00045%,Annual official estimate
191,San Marino,33005,"December 31, 2015",0.00045%,Monthly official estimate
--,Turks and Caicos Islands (UK),31458,"January 25, 2012",0.00043%,2012 census result
--,British Virgin Islands (UK),28514,"July 1, 2013",0.00039%,Official estimate
--,Bonaire (Netherlands),18905,"January 1, 2015",0.00026%,Official estimate
--,Cook Islands,18100,"March 1, 2016",0.00025%,Official quarterly estimate
192,Palau,17950,"July 1, 2015",0.00024%,Annual official estimate
--,Anguilla (UK),13452,"May 11, 2011",0.00018%,Preliminary 2011 census result
--,Wallis and Futuna (France),11750,"July 1, 2015",0.00016%,Annual official estimate
193,Tuvalu,10640,"November 4, 2012",0.00014%,2012 census result
194,Nauru,10084,"October 30, 2011",0.00014%,2011 census result
--,Saint Barthélemy (France),9417,"January 1, 2015",0.00013%,Annual official estimate
--,Saint Pierre and Miquelon (France),6286,"January 1, 2015",0.000086%,Annual official estimate
--,Montserrat (UK),4922,"May 12, 2011",0.000067%,2011 census result
--,"Saint Helena, Ascension and Tristan da Cunha (UK)",4255,"February 10, 2008",0.000058%,2008 census result
--,Sint Eustatius (Netherlands),3877,"January 1, 2015",0.000053%,Official estimate
--,Falkland Islands (UK),2563,"April 15, 2012",0.000035%,2012 census result
--,Norfolk Island (Australia),2302,"August 9, 2011",0.000031%,2011 census result
--,Christmas Island (Australia),2072,"August 9, 2011",0.000028%,2011 census result
--,Saba (Netherlands),1811,"January 1, 2015",0.000025%,Official estimate
--,Niue,1470,"July 1, 2015",0.000020%,Annual official estimate
--,Tokelau (NZ),1411,"October 18, 2011",0.000019%,2011 census result
195,Vatican City,842,"January 1, 2014",0.000011%,Official estimate
--,Cocos (Keeling) Islands (Australia),550,"August 9, 2011",0.0000075%,2011 census result
--,Pitcairn Islands (UK),56,"July 1, 2014",0.00000076%,Official estimate

In [36]:
ugly_country_names = dfs[2]['Country (or dependent territory)']

In [48]:
populations = dfs[2].copy()
populations['Name'] = ugly_country_names.str.extract("([^[(]*)").str.strip()

/Users/allenbyron/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  from ipykernel import kernelapp as app

In [52]:
populations[populations.Name == 'China'].Population.median()

1378640000.0

In [58]:
mdf = drinks.merge(populations, left_on='country', right_on='Name')
mdf

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent,Country (or dependent territory),Population,Date,% of world population,Source,Name
0,Afghanistan,0,0,0,0.0,AS,Afghanistan,27657145,"July 1, 2016",0.38%,Annual official estimate,Afghanistan
1,Albania,89,132,54,4.9,EU,Albania,2886026,"January 1, 2016",0.039%,Annual official estimate,Albania
2,Algeria,25,0,14,0.7,AF,Algeria,40400000,"July 1, 2016",0.55%,Official annual projection,Algeria
3,Andorra,245,138,312,12.4,EU,Andorra,78014,"December 31, 2015",0.0011%,Annual official estimate,Andorra
4,Angola,217,57,45,5.9,AF,Angola,24383301,"May 16, 2014",0.33%,Preliminary 2014 census result,Angola
5,Argentina,193,25,221,8.3,SA,Argentina,43590400,"July 1, 2016",0.59%,Official annual projection,Argentina
6,Armenia,21,179,11,3.8,EU,Armenia,2995100,"July 1, 2016",0.041%,Quarterly official estimate,Armenia
7,Australia,261,72,212,10.4,OC,Australia,24182100,"September 8, 2016",0.329%,Official population clock,Australia
8,Austria,279,75,191,9.7,EU,Austria,8741753,"July 1, 2016",0.119%,Quarterly provisional figure,Austria
9,Azerbaijan,21,46,5,1.3,EU,Azerbaijan,9755500,"July 1, 2016",0.13%,Official estimate,Azerbaijan
10,Bahamas,122,176,51,6.3,NaN,Bahamas,378040,"July 1, 2016",0.0051%,Official projection,Bahamas
11,Bahrain,42,63,7,2.0,AS,Bahrain,1404900,"July 1, 2016",0.019%,Official annual projection,Bahrain
12,Bangladesh,0,0,0,0.0,AS,Bangladesh,161047000,"September 8, 2016",2.19%,Official population clock,Bangladesh
13,Barbados,143,173,36,6.3,NaN,Barbados,285000,"July 1, 2016",0.0039%,UN projection,Barbados
14,Belarus,142,373,42,14.4,EU,Belarus,9498700,"April 1, 2016",0.129%,Quarterly official estimate,Belarus
15,Belgium,295,84,212,10.5,EU,Belgium,11323925,"July 1, 2016",0.15%,Monthly official estimate,Belgium
16,Belize,263,114,8,6.8,NaN,Belize,375909,"April 1, 2016",0.0051%,Official estimate,Belize
17,Benin,34,4,13,1.1,AF,Benin,10653654,"July 1, 2016",0.15%,Official projection,Benin
18,Bhutan,23,0,0,0.4,AS,Bhutan,777820,"September 8, 2016",0.0106%,Official population clock,Bhutan
19,Bolivia,167,41,8,3.8,SA,Bolivia,10985059,"July 1, 2016",0.15%,Official projection,Bolivia
20,Botswana,173,35,35,5.4,AF,Botswana,2230905,"July 1, 2016",0.03%,Official annual projection,Botswana
21,Brazil,245,145,16,7.2,SA,Brazil,206625000,"September 8, 2016",2.81%,Official population clock,Brazil
22,Brunei,31,2,1,0.6,AS,Brunei,411900,"July 1, 2014",0.0056%,Official estimate,Brunei
23,Bulgaria,231,252,94,10.3,EU,Bulgaria,7153784,"December 31, 2015",0.097%,Official estimate,Bulgaria
24,Burkina Faso,25,7,7,4.3,AF,Burkina Faso,19034397,"July 1, 2016",0.26%,Annual official projection,Burkina Faso
25,Burundi,88,0,0,6.3,AF,Burundi,10114505,"July 1, 2016",0.14%,Official annual projection,Burundi
26,Cambodia,57,65,1,2.2,AS,Cambodia,15626444,"July 1, 2016",0.21%,Official annual projection,Cambodia
27,Cameroon,147,1,4,5.8,AF,Cameroon,22709892,"July 1, 2016",0.31%,Annual official projection,Cameroon
28,Canada,240,122,100,8.2,NaN,Canada,36520100,"September 8, 2016",0.497%,Official estimate,Canada
29,Central African Republic,17,2,1,1.8,AF,Central African Republic,4998000,"July 1, 2016",0.068%,UN projection,Central African Republic
...,...,...,...,...,...,...,...,...,...,...,...,...
147,Spain,284,157,112,10.0,EU,Spain,46438422,"January 1, 2016",0.63%,Official estimate,Spain
148,Sri Lanka,16,104,0,2.2,AS,Sri Lanka,20966000,"July 1, 2015",0.29%,Official estimate,Sri Lanka
149,Sudan,8,13,0,1.7,AF,Sudan,41176000,"July 1, 2016",0.56%,Official annual projection,Sudan
150,Suriname,128,178,7,5.6,SA,Suriname,541638,"August 13, 2012",0.0074%,Final 2012 census result,Suriname
151,Swaziland,90,2,2,4.7,AF,Swaziland,1132657,"July 1, 2016",0.015%,Official projection,Swaziland
152,Sweden,152,60,186,7.2,EU,Sweden,9920881,"July 3, 2016",0.14%,Monthly official estimate,Sweden
153,Switzerland,185,100,280,10.2,EU,Switzerland,8341600,"March 31, 2016",0.114%,Quarterly provisional figure,Switzerland
154,Syria,5,35,16,1.0,AS,Syria,18564000,"July 1, 2016",0.25%,UN projection,Syria
155,Tajikistan,2,15,0,0.3,AS,Tajikistan,8551000,"January 1, 2016",0.116%,Official estimate,Tajikistan
156,Thailand,99,258,1,6.4,AS,Thailand,65729098,"December 31, 2015",0.89%,Annual official estimate,Thailand
157,Macedonia,106,27,86,3.9,EU,Macedonia,2071278,"December 31, 2015",0.028%,Official estimate,Macedonia
158,Togo,36,2,19,1.3,AF,Togo,7143000,"July 1, 2016",0.097%,Official estimate,Togo
159,Tonga,36,21,5,1.1,OC,Tonga,103252,"November 30, 2011",0.0014%,2011 census result,Tonga
160,Tunisia,51,3,20,1.3,AF,Tunisia,11154400,"July 1, 2015",0.15%,Official estimate,Tunisia
161,Turkey,51,22,7,1.4,AS,Turkey,78742000,"December 31, 2015",1.07%,Annual official estimate,Turkey
162,Turkmenistan,19,71,32,2.2,AS,Turkmenistan,4751120,"December 26, 2012",0.065%,Preliminary 2012 census result,Turkmenistan
163,Tuvalu,6,41,9,1.0,OC,Tuvalu,10640,"November 4, 2012",0.00014%,2012 census result,Tuvalu
164,Uganda,45,9,0,8.3,AF,Uganda,36861000,"July 1, 2016",0.5%,Official annual projection,Uganda
165,Ukraine,206,237,45,8.9,EU,Ukraine[Note 7],42658149,"July 1, 2016",0.58%,Monthly official estimate,Ukraine
166,United Arab Emirates,16,135,5,2.8,AS,United Arab Emirates,9856000,"July 1, 2016",0.13%,Official annual projection,United Arab Emirates
167,United Kingdom,219,126,195,10.4,EU,United Kingdom,65110000,"July 1, 2015",0.89%,Annual official estimate,United Kingdom
168,Tanzania,36,6,1,5.7,AF,Tanzania[Note 6],55155000,"July 1, 2016",0.75%,UN projection,Tanzania
169,Uruguay,115,35,220,6.6,SA,Uruguay,3480222,"June 30, 2016",0.047%,Annual official estimate,Uruguay
170,Uzbekistan,25,101,8,2.4,AS,Uzbekistan,31575300,"January 1, 2016",0.43%,Official estimate,Uzbekistan
171,Vanuatu,21,18,11,0.9,OC,Vanuatu,277500,"July 1, 2015",0.0038%,Annual official estimate,Vanuatu
172,Venezuela,333,100,3,7.7,SA,Venezuela,31028700,"July 1, 2016",0.42%,Official annual projection,Venezuela
173,Vietnam,111,2,1,2.0,AS,Vietnam,92700000,"July 1, 2016",1.26%,Annual official projection,Vietnam
174,Yemen,6,0,0,0.1,AS,Yemen,27478000,"July 1, 2016",0.37%,UN projection,Yemen
175,Zambia,32,19,4,2.5,AF,Zambia,15933883,"July 1, 2016",0.22%,Official annual projection,Zambia
176,Zimbabwe,64,18,4,4.7,AF,Zimbabwe,14240168,"July 1, 2016",0.19%,Official annual projection,Zimbabwe

In [59]:
mdf.country.count()

177

In [60]:
drinks.country.count()

193

In [68]:
drinks_set = set(drinks.country)
mdf_set = set(mdf.country)
drinks_set - mdf_set

{'Antigua & Barbuda',
 'Bosnia-Herzegovina',
 'Cabo Verde',
 'Congo',
 "Cote d'Ivoire",
 'DR Congo',
 'Gambia',
 'Micronesia',
 'Russian Federation',
 'Sao Tome & Principe',
 'St. Kitts & Nevis',
 'St. Lucia',
 'St. Vincent & the Grenadines',
 'Timor-Leste',
 'Trinidad & Tobago',
 'USA'}

# DBs disagree about the names of countries. We have three options:

## Option 1 | Repair after the fact
we will use and outer join instead of an inner join.

In [71]:
animals = pd.DataFrame(
    data = {
        'name': ['Chong', 'Alex', 'Byron', 'James'],
        'fav_animal': ['frog', 'panda', 'dog', 'dog']
    }
)

In [72]:
animals

  fav_animal   name
0       frog  Chong
1      panda   Alex
2        dog  Byron
3        dog  James

In [74]:
fav_colors = pd.DataFrame(
    data = {
        'name': ['Guarav', 'James', 'Chong', 'Alex'],
        'color': ['Green', 'Blue', 'Orange', 'Blue']
    }
)

fav_colors

    color    name
0   Green  Guarav
1    Blue   James
2  Orange   Chong
3    Blue    Alex

In [76]:
animals.merge(fav_colors, on='name', how='left')

  fav_animal   name   color
0       frog  Chong  Orange
1      panda   Alex    Blue
2        dog  Byron     NaN
3        dog  James    Blue

In [89]:
drinks_outer = drinks.merge(populations,
                           left_on='country',
                           right_on='Name',
                           how='left').copy()

In [90]:
len(drinks)

193

In [99]:
set(drinks_outer[drinks_outer.Population.isnull()].country)

{'Antigua & Barbuda',
 'Bosnia-Herzegovina',
 'Cabo Verde',
 'Congo',
 "Cote d'Ivoire",
 'DR Congo',
 'Gambia',
 'Micronesia',
 'Russian Federation',
 'Sao Tome & Principe',
 'St. Kitts & Nevis',
 'St. Lucia',
 'St. Vincent & the Grenadines',
 'Timor-Leste',
 'Trinidad & Tobago',
 'USA'}

In [100]:
mappings = {'Congo': 'DRC', 'USA': 'United States'}

In [ ]:
##########What to do here???????

In [ ]:
######Not sure if I follow this example

In [92]:
populations.Name[populations.Name.str.startswith('Antigua')]

Rank
184    Antigua and Barbuda
Name: Name, dtype: object

In [95]:
populations.Population[populations.Name.str.startswith('Antigua')].median()

86295.0

In [97]:
antiqua_pop = populations.Population[populations.Name.str.startswith('Antigua')].median()
drinks_outer[drinks_outer.country.str.startswith('Antigua')].Population = antiqua_pop

In [ ]:
######Not sure if I follow this example

## Option 2 | Fix the drinks table

In [101]:
def cor_wrong_drinks_name(x):
    if x in mappings:
        retrun mappings[x]
    return x

SyntaxError: invalid syntax (<ipython-input-101-2ce910509c60>, line 3)

## Option 3 | Fix the Wikipedia table